# Generated by Django 6.0.8 on 2026-08-07 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="performance",
            old_name="cinema_hall",
            new_name="theatre_hall",
        ),
    ]
